---
# tasks file for docker

    
- name: install packages needed
  dnf:
    name: "{{ item }}"
    state: present 
  with_items:
    - lvm2
    - device-mapper
    - curl 
    - device-mapper-persistent-data
    - device-mapper-event 
    - device-mapper-libs
    - device-mapper-event-libs

- name : Add Docker Repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo


- name: install docker
  dnf:
   name: docker-ce
   state: present

- name: start and enable docker services
  service:
    name: "docker"
    state: started
    enabled: yes